upto 346
vishvAsa/AgamaH_vaiShNavaH pull request #1
Opened 2023-02-13 12:45 UTC by Dhunee

यथाज्ञानं मूलव्याख्ययोर्योजनं व्यधायि । सत्सु दोषेषु कृपया सूच्यताम् ।

धन्यवादाः

2023-02-13 13:19 UTC, vvasuki requested changes
भवत्या प्रत्येकस्मिन् कार्यदिने ऽवश्यम् आकर्षणाभ्यर्थनम् प्रेषणीयम्। विलम्ब्य सङ्गृह्य प्रेषयामीति सङ्कल्पो मास्तु। परीक्षणसौकार्याय लघुकार्यखण्डानीष्यन्ते।

2023-02-13 13:19 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +</details>
इयं पङ्क्तिः, ६०-तमा च निष्कासनीया। मूलम् एवाग्रिमे पृष्ठे ऽनुवर्तत इति कारणेन 
`</details>` इति पिधायः `<details><summary>मूलम्</summary>` इति पुनर् आरम्भो न स्यात्।

2023-02-13 13:54 UTC, vvasuki requested changes

2023-02-13 13:54 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> स च प्रार्थनामन्त्रः
`>`चिह्नम् अत्र न स्यात्।

2023-02-13 13:54 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> नियतेन्द्रियस्समाहितोऽतिक्रान्तमनन्तं कालं निरर्थकमवलोक्य निर्वेदं परं गच्छेत् - निर्वेदप्रकाराश्च विविधास्तत्तत् संहिताविशेषेष्वनुसन्धेयाः ।
"नियतेन्द्रिय…" इत्यारभ्य "विस्तरेणोद्धृतं चैतद्वङ्गिवंशेश्वरैः" इति यावद् उद्धरणम्। मध्ये रिक्ताः पङ्क्तयः। तेषु १२४ तमायां `>`चिह्नं विस्मृतम् इति भाति। एवम् अन्येष्व् अपि दीर्घोद्धरणेषु परीक्ष्य समीकुर्यात्।

2023-02-14 11:00 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +<details><summary>आह्निकार्थप्रकाशिका</summary>
निष्कासिता ।

2023-02-14 11:08 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> नियतेन्द्रियस्समाहितोऽतिक्रान्तमनन्तं कालं निरर्थकमवलोक्य निर्वेदं परं गच्छेत् - निर्वेदप्रकाराश्च विविधास्तत्तत् संहिताविशेषेष्वनुसन्धेयाः ।
ओम्

2023-02-14 11:09 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> स च प्रार्थनामन्त्रः
निष्कासितम्

2023-02-14 11:10 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +</details>
निष्कासिता

2023-02-14 16:16 UTC, vvasuki requested changes

2023-02-14 16:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
उपरि दृश्यमानानि वाक्यानि dillinger.io इत्यस्मिन् स्थापयित्वा पश्यतु। 

```
>> ब्राह्मे मुहूर्ते सत्वस्थो हरिर्हरिरिति ब्रुवन् ।  
उत्थाय शयने तत्र समासीनस्समाहितः ॥  
व्यर्थं वीक्ष्य गतं कालं निर्विद्याहमितः परम् ।
>
इति विस्तरेणोद्धृतं चैतद्वङ्गिवंशेश्वरैः
>
इत्यादि । 
```

2023-02-14 16:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> स च प्रार्थनामन्त्रः
निष्कासितं क्व? अधुनापि दृश्यते? उत्तरलेखनात् परम् अवश्यम् commit_push इति करणीयम्।

2023-02-14 16:55 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
image.png

एवं दर्शयति

2023-02-14 16:59 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> स च प्रार्थनामन्त्रः
ओम्

2023-02-15 16:52 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
तज्जालक्षेत्रं दुष्टम् इति भाति। https://stackedit.io/app# इति स्पष्टतरम् भवति।

2023-02-15 16:54 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +</details>
पुनर् अत्रानुद्घाटितस्य पिधानम्। स एव दोषो यत्परिहारे snippets-विषयः कश्चनोक्तः। साधयित्वैव प्रतिवदत्व् इह, न ततः पूर्वम् (भ्रमवारणाय)।

2023-02-15 18:17 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +</details>
समीकृतम् ।

2023-02-17 11:54 UTC, vvasuki requested changes

2023-02-17 11:54 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  उपादानञ्च इति पाठान्तरम् ।
पादटिप्पनीतन्त्रं सम्यङ् नाधिगतम् इति भाति। https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Footnotes/  इत्य् अवेक्षताम्। ततः सर्वत्र समीकरोतु।

2023-02-17 11:54 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +भव[[र?]]द्वाजः -
आम्, समीकरोतु।

2023-02-20 09:32 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +भव[[र?]]द्वाजः -
ओम्

2023-02-20 11:35 UTC, merged