upto 1075
vishvAsa/AgamaH_vaiShNavaH pull request #2
Opened 2023-02-21 07:34 UTC by Dhunee

2023-02-21 08:16 UTC, vvasuki requested changes

2023-02-21 08:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
अत्र रिक्तपङ्क्तयो ऽप्य् उद्धरणाङ्गानि खलु? तथा सति तेष्व् अपि >-चिह्नं स्यात्।  https://stackedit.io/app# इत्यत्र द्वित्रैः प्रयोगैः स्पष्टतरम् भवति।
इदञ्चोद्धरणम् ` सर्वपापप्रणाशनम् ॥ इति` इति यावद् वर्तत इति गण्यताम्।

2023-02-21 08:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति नित्यग्रन्धे[[न्थे??]]षु बहुषु सत्त्वात् अत्र तदुक्तिः ।
आम्, समीकरोतु

2023-02-21 08:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति स्मृतिवचनात् प्रातर्मृत्तिकास्नानवि[[नि??]]षेधेऽपि
आम्- समीकरोतु।

2023-02-21 08:16 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
उता अपि पङ्क्तय उद्धरणाङ्गाः खलु। तर्हि >-चिह्नविन्यासे ऽवदधातु।  https://stackedit.io/app# इत्यत्र द्वित्रैः प्रयोगैः स्पष्टतरम् भवति।

2023-02-21 10:23 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
om

2023-02-21 10:24 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति नित्यग्रन्धे[[न्थे??]]षु बहुषु सत्त्वात् अत्र तदुक्तिः ।
ओम्

2023-02-21 10:24 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति स्मृतिवचनात् प्रातर्मृत्तिकास्नानवि[[नि??]]षेधेऽपि
ओम्

2023-02-21 10:30 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
उता अपि पङ्क्तय उद्धरणाङ्गाः खलु - इदं नावगतम्

2023-02-21 10:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
टङ्कनदोषो मार्जितः - पुनः पश्यतु।

2023-02-22 01:23 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
ह्य एव अग्रिमे पृष्ठे अनुवर्तमानाः श्लोका अपि उद्धरणेऽन्तर्भाविताः । परन्तु अत्र तन्न दर्शयति । यानि परिष्करणानि ह्यः साधितानि तानीह न दर्शयत्येव । कुतः?

2023-02-22 01:27 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
> समाचम्य शुचौ देशे गृह्णीयात् स्नानमृत्तिकाम् ।  
अस्त्राभिमृष्टैः काष्ठाद्यैः स्वमन्त्रेणैव वाग्यतः ॥  
तां विभज्य द्विधा तीरे न्यस्याभ्यज्य मृदोस्तयोः ।  
भागेनैकेन महता देहं प्रक्षाल्य सर्वतः ॥  
ततो जलं प्रविश्य त्रिर्निमज्ज्योत्तीर्य संयतः ।  
आसीनश्शोधिते तीरे समाचम्य यथाविधि ॥  
अन्यं मृद्भागमादाय न्यसेद्दक्षिणपाणिना ।  
वामपाणितलस्यादौ मध्येऽन्ते च समन्त्रकम् ॥  
तत आदिममृद्भागमन्तर्वारिणि निक्षिपेत् ।  
पीठार्थमागमिष्यन्त्या गङ्गायाः स्नातुमात्मनः ॥

[[52]]

> मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।  
साङ्गुष्ठतर्जन्यास्त्रेण स्नानविघ्नकरान् क्षिपेत् ॥  
पश्चादग्रिमभागेन स्वगात्रमनुलिप्य च ।  
स्वमन्त्रेणैव पाणिभ्यां प्रविशेच्च जलं ततः ॥  
पाणिभ्यां जलमादाय तीर्थायार्घ्यप्रदित्सया ।  
तिष्ठन्नावाहयेद्गङ्गां सर्वतीर्थसमन्विताम् ॥  
आवाहयामि त्वां देवि स्नानार्थमिह सुन्दरि ।  
एहि गङ्गे नमस्तुभ्यं सर्वतीर्थसमन्विते ॥  
विष्णुवामपदाङ्गुष्ठनखस्रोतोविनिस्सृते ।  
तद्भक्तिविघ्नरूपा त्वं गङ्गे मां मोचयैनसः ॥  
एवमुच्चार्य दत्वार्घ्यं गङ्गायै सुरसिन्धवे ।  
तोयमादाय पाणिभ्यां त्रिर्मन्त्रेणाभिमन्त्र्य तत् ॥  
त्रिः पञ्चकृत्वो वा तेन सिञ्चेन्मूर्धानमात्मनः ।  
ततो दक्षिणहस्तेन समादाय जलं शुचि ॥  
त्रिर्वाथ पञ्चकृत्वो वा स्वमन्त्रेणाभिमन्त्र्य तत् ।  
पीत्वा पुनः समाचम्य प्रोक्षयेदात्मनस्तनुम् ॥ 

इति वङ्गिवंशेश्वरवचनान्यत्रानुसन्धेयानि । 

> स्वात्मानं सम्प्रोक्ष्य परिषिच्य 

इति नित्यग्रन्थेषु बहुषु सत्त्वात् अत्र तदुक्तिः । 

> गुरोर्नाम सदा जपेत् 

इति प्रमाणादाचाराच्च स्नानसमये स्वाचार्यप्रभृति भगवदन्ताचार्याणां श्रीमत्पदपूर्वकाणि नमोऽन्तानि चतुर्थ्यन्तनामानि कीर्तनीयानि । 

> गुरुपादोदकं सिञ्चेत् शिर आदौ तु पूर्ववत् 

इति वर्णाश्रमकाण्डस्थवचनमिहानुसन्धेयम् ।

यत्तु अन्योक्तम् - 

> न प्रातर्मृत्तिकास्नानम् 

इति स्मृतिवचनात् प्रातर्मृत्तिकास्नाननिषेधेऽपि 

> वक्ष्यमाणक्रमेण जलावगाहनादि 

इत्यादिनाचार्यपादैः प्रातर्मृत्तिकास्नानविधानेन पञ्चरात्रप्राबल्यावगमात् धर्मशास्त्रविहितस्रानं तदनभिमतमिति । तदयुक्तम् - 

> प्रातः सङ्क्षेपतः स्नानं होमार्थं तु विधीयते ।  
मृन्मन्त्रविधिनिष्पाद्यं मध्याह्ने तु सविस्तरम् ।  
कल्पत्वाद्धोमकालस्य बहुत्वात् स्नानकर्मणः ॥ 

इति रत्नाकरस्थदक्षकात्यायनवचनतो बहुमन्त्रयुक्तमृत्तिकास्नाननिषेधेन तत्र 

> न प्रातर्मृत्तिकास्नानम् 

इति सामान्यनिषेधस्य छागपशुन्यायेन पर्यवसानेन भगवच्छास्त्रविहितलघुमन्त्रकरणकसंक्षिप्तमृत्तिकास्नाननिषेधाप्रसक्त्या विरोधाभावात् । धर्मशास्त्रविहितस्नानमप्याचार्यपादाभिमतमिति सत्पथरक्षायां सम्यक् स्थापितमस्माभिः ।
</details>

इत्थमेव ननु इष्टम् ? इदं ह्यः परिष्कृतम् इति commit कृतम् ।

2023-02-22 01:51 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +मध्यमेन मृदंशेन बध्नीयात्सकला दिशः ।
तादृशम् एव। तत ऊर्ध्वं किञ्चित् टॆलिग्राम्य् उक्तम्। (प्रायेण commit-push इति न कृतम् इति ह्यो दर्शितं नाभूद् अत्र)

2023-02-22 07:08 UTC, vvasuki requested changes

2023-02-22 07:08 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +कटिसूत्रं च कौपीनमन्त्र[[??]]रीयं क्रमेण तु ॥
aam = रेफं निवारयतु।

2023-02-22 07:08 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> **अच्छिन्ने**
एकस्य शब्दस्य कृत उद्धरणपङ्क्त्तिर् मास्तु - "-चिह्ने प्रयुङ्क्ताम्।

2023-02-22 07:08 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> देवस्य त्वा सवितुः व्रसवेऽश्विनोर्बाहुभ्यां पूष्णो[[??]] हस्ताभ्यामादद
?? इति कुतः?

2023-02-22 07:08 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> शुचीवोहव्यामरुतश्शुचीनां शुचिँ हिनोम्यध्वरँ शुचिभ्यः । ऋतेन सत्यमृतसाप[[??]] आयन् शुचिजन्मानश्शुचयः पावका
?? इति कुतः?

2023-02-22 11:58 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +कटिसूत्रं च कौपीनमन्त्र[[??]]रीयं क्रमेण तु ॥
om

2023-02-22 11:59 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> **अच्छिन्ने**
om

2023-02-22 12:00 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> देवस्य त्वा सवितुः व्रसवेऽश्विनोर्बाहुभ्यां पूष्णो[[??]] हस्ताभ्यामादद
nivaaritam

2023-02-22 12:00 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> शुचीवोहव्यामरुतश्शुचीनां शुचिँ हिनोम्यध्वरँ शुचिभ्यः । ऋतेन सत्यमृतसाप[[??]] आयन् शुचिजन्मानश्शुचयः पावका
nivaaritam

2023-02-22 12:07 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> शुचीवोहव्यामरुतश्शुचीनां शुचिँ हिनोम्यध्वरँ शुचिभ्यः । ऋतेन सत्यमृतसाप[[??]] आयन् शुचिजन्मानश्शुचयः पावका
सन्देहे सति न हि निवारणीयम्।  सद्य इमां स्थापयतु सस्वराम् -

शुची॑ वो ह॒व्या म॑रुतः॒ शुची॑नां॒ शुचिं॑ हिनोम्यध्व॒रं शुचि॑भ्यः ।  
ऋ॒तेन॑ स॒त्यमृ॑त॒साप॑ आय॒ञ्छुचि॑जन्मानः॒ शुच॑यः पाव॒काः ॥

2023-02-22 15:11 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> शुचीवोहव्यामरुतश्शुचीनां शुचिँ हिनोम्यध्वरँ शुचिभ्यः । ऋतेन सत्यमृतसाप[[??]] आयन् शुचिजन्मानश्शुचयः पावका
ओम्

2023-02-23 07:34 UTC, vvasuki requested changes
सर्वत्र

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति, कण्ठभूषणे गृहीकौपीननिषेधप्रमाणं नोदाहृतमिति । पूर्वोक्तप्रमाणादर्शनेऽपि होलकाधिकरणन्यायेन गृही[[??]]कौपीनधारणस्य शिष्टाचारमूलत्वेन त्याज्यत्वं न सम्भवति ।
गृहिकौपीनधारणस्य 

इति समीकरोतु।

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अथ धर्माशास्त्रोक्तस्नानानि वक्तुमूर्ध्वमुण्ड्र[[पुण्ड्र??]]धारणानां वक्ष्यमाणत्वमाह **ततो वक्ष्यमाणे**त्यादिना ।
आम्

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इत्यादिना भगवन्तमनुज्ञाप्य जलं प्रविश्य त्रिर्निमज्ज्य, उदुत्तमं वरुणपाशमस्मदवाधमं विमध्यमँ श्रधाया[[??]] अथावयमादित्यव्रतेतवानागसो[[??]] अदितये स्याम, अस्कभ्नाद्यामृषभो अन्तरिक्षममिमीत वरिमाणं पृथिव
उदु॑त्त॒मं व॑रुण॒ पाश॑म॒स्मदवा॑ध॒मं वि म॑ध्य॒मं श्र॑थाय ।  
अथा॑ व॒यमा॑दित्य व्र॒ते तवाना॑गसो॒ अदि॑तये स्याम ॥

अपि च - https://vishvasa.github.io/devaH/AryaH/hindukaH/varuNaH/Rk/yach_chid_hi_te/

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +> दुर्मित्रास्तस्मै भूया सु[[सू??]]र्योऽस्मान् द्वेष्टि यञ्च वयं द्विष्म
भूयासुर् योऽस्मान्

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +ते गृह्णन्तु मया दत्तं वस्त्रा[[??]]निष्पीडनोदकम् ॥
वस्त्र

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति वङ्ग[[ङ्गि??]]वंशेश्वरोक्तं मूलमन्त्रप्राणायामजपरूपं मन्त्रस्नानं
आम्, शोधयतु

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अनन्तादित्यसङ्काशं [[??]] चतुर्भुजम् ॥
वासुदेवं चतुर्भुजम्

इति गूगलन्वेषणेन । तथा पूरयतु।

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अथ गौणस्नान्या[[नमा??/नान्या?]]ह – **वारुणस्नानाशक्तावि**त्यादिना । योगयाज्ञवल्क्यः -
गौणस्नानान्याह

2023-02-23 07:34 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +<details><summary>मूलम्</summary>
`<details><summary>मूलम्` इत्यस्य स्थाने सर्वत्र `<details open><summary>मूलम्` इति करोतु। Find replace तन्त्रेण क्षणसाध्यम्।

2023-02-23 09:00 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इत्यादिना भगवन्तमनुज्ञाप्य जलं प्रविश्य त्रिर्निमज्ज्य, उदुत्तमं वरुणपाशमस्मदवाधमं विमध्यमँ श्रधाया[[??]] अथावयमादित्यव्रतेतवानागसो[[??]] अदितये स्याम, अस्कभ्नाद्यामृषभो अन्तरिक्षममिमीत वरिमाणं पृथिव
https://vishvasa.github.io/devaH/AryaH/hindukaH/varuNaH/Rk/yach_chid_hi_te/ - अत्र विद्यमानं अभिगमने योज्यं वा?

2023-02-23 09:01 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति, कण्ठभूषणे गृहीकौपीननिषेधप्रमाणं नोदाहृतमिति । पूर्वोक्तप्रमाणादर्शनेऽपि होलकाधिकरणन्यायेन गृही[[??]]कौपीनधारणस्य शिष्टाचारमूलत्वेन त्याज्यत्वं न सम्भवति ।
ओम्

2023-02-23 09:01 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अथ धर्माशास्त्रोक्तस्नानानि वक्तुमूर्ध्वमुण्ड्र[[पुण्ड्र??]]धारणानां वक्ष्यमाणत्वमाह **ततो वक्ष्यमाणे**त्यादिना ।
समीकृतम्

2023-02-23 09:09 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +ते गृह्णन्तु मया दत्तं वस्त्रा[[??]]निष्पीडनोदकम् ॥
समीकृतम्

2023-02-23 09:09 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इति वङ्ग[[ङ्गि??]]वंशेश्वरोक्तं मूलमन्त्रप्राणायामजपरूपं मन्त्रस्नानं
शोधितम्

2023-02-23 09:10 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अनन्तादित्यसङ्काशं [[??]] चतुर्भुजम् ॥
पूरितम् ।

2023-02-23 09:10 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +अथ गौणस्नान्या[[नमा??/नान्या?]]ह – **वारुणस्नानाशक्तावि**त्यादिना । योगयाज्ञवल्क्यः -
समीकृतम्

2023-02-23 09:17 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इत्यादिना भगवन्तमनुज्ञाप्य जलं प्रविश्य त्रिर्निमज्ज्य, उदुत्तमं वरुणपाशमस्मदवाधमं विमध्यमँ श्रधाया[[??]] अथावयमादित्यव्रतेतवानागसो[[??]] अदितये स्याम, अस्कभ्नाद्यामृषभो अन्तरिक्षममिमीत वरिमाणं पृथिव
"यत् कित्किञ्चेदं[[??]] वरुण दैव्ये जनेऽभिद्रोहं मनुष्याश्चरामसि । अचित्तीयत्तवधर्मायुयोविम मानस्तस्मादेनसो देव रीरिषः। कितवासो यद्रिरिपुर्न दिवि यद्वाघासत्यमुतयन्नविद्म । सर्वाता विष्यशिथिरेवदेवाथाते-स्याम वरुण प्रियासः" इति भागस्य स्थाने, 

```
<div class="js_include" url="/devaH/AryaH/hindukaH/varuNaH/Rk/yach_chid_hi_te/"  newLevelForH1="5" includeTitle="false"> </div>
```

इति पङ्क्तिं स्थापयतु।

2023-02-23 09:33 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +इत्यादिना भगवन्तमनुज्ञाप्य जलं प्रविश्य त्रिर्निमज्ज्य, उदुत्तमं वरुणपाशमस्मदवाधमं विमध्यमँ श्रधाया[[??]] अथावयमादित्यव्रतेतवानागसो[[??]] अदितये स्याम, अस्कभ्नाद्यामृषभो अन्तरिक्षममिमीत वरिमाणं पृथिव
ओम्

2023-02-28 11:37 UTC, vvasuki requested changes

2023-02-28 11:37 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
> +जत्रौ दक्षिणकण्ठपार्श्वे चतुरङ्गुलमूर्ध्वं विस्तृतं, वामकुक्षिपार्श्वे वामबाहुमूले वामजत्रौ दक्षिणवत्, जघनोपरि पृष्ठभागे त्र्यङ्गुलमायतं विस्तृतञ्च, ककुदे त्र्यङ्गुलमायतं विस्तृतञ्च, ककुदे त्र्यङ्गुल
त्र्यङ्गुलम् इति स्यात् खलु?

आवृत्तं वाक्यखण्डं निष्कासयतु।

2023-03-02 08:06 UTC, merged