upto 53
vishvAsa/AgamaH_vaiShNavaH pull request #59
Opened 2023-11-30 17:30 UTC by Dhunee

2023-12-01 01:45 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sa/aNNangarAchAryaH/01.md
> +> जयति पुमान् पर एकः श्रुतिशतपरिगीतवैभव श्रीमान् ।
नेदम् उचितम्। इयं सञ्चिका नैव परिवर्तनीया। शुद्धाः पङ्क्तयस् तु shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH इत्यत्रैव यथास्थानं निवेशनीयाः शोधनीयाश् च, यथा ट्रॆल्लॊ-द्वारापि स्मारितम्।

2023-12-02 05:54 UTC, vvasuki requested changes

2023-12-02 05:54 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/03_padArthasamuddeshaH.md
> +अजडम् **पराग्** अपि तथा – नित्य-भूतिर् धर्मभूतज्ञानं चेति ।
विश्वास-प्रस्तुति-भागान् न परिवर्तयेत् पाठभेदेन। व्याकरणादिदोषे सति तु परिष्कारे नास्ति हानिः, यद्य् अपि दोषवैरल्यात् तत्परीक्षणे ऽधिकम् अवधानं न दद्यात्।

2023-12-02 05:54 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/03_padArthasamuddeshaH.md
> +३. अजडं तु द्विविधम् – पराक् प्रत्यक् चेति । परागपि द्विधा - नित्यभूतिः धर्मभूतज्ञानं चेति ।
मूलभगे व्यत्यासे सति पाठान्तरं दर्शनीयम्, यथात्र - 

```
अजडम् परागपि तथा – नित्यविभूतिर् धर्मभूतज्ञानं चेति । (परागपि द्विधा - नित्यभूतिः धर्मभूतज्ञानं चेति ।)

2023-12-02 05:54 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/01_mangalAcharaNam.md
टीकारम्भे ऽण्णङ्गराचार्यस्य श्लोकाद्य् अवर्तन्त? तथा सति, तान् पञ्चमपङ्क्तेः प्राक् संयोजयतु

2023-12-02 05:54 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/02_tattvaikyasya_pratijnA.md
> +१. श्रीमन्नारायण एव चिदचिद्विशिष्टोऽद्वैतं तत्त्वम्, भक्तिप्रपत्तिभ्यां प्रसन्नः स एवोपायः, अप्राकृतदेशविशिष्टः स एव प्राप्यः इति वेदान्तवावाक्यैः प्रतिपादयताम् श्रीव्यासबोधायन-गुहदेवभारुचिब्रह्मनन्द
अत्रापि (अग्रिमसञ्चिकायाम् उक्तया रीत्या) पाठभेदम् (एवोपायः) इत्य् आवरणेन दर्शयतु। एवं ("चिदचिद्विशिष्टोऽद्वैतं तत्त्वम्") इत्यपि। 

"भक्तिप्रपत्तिभ्यां" परिष्खारो नापेक्षितः - अनुस्वारस्य ययि परसवर्ण इति यतः। कृतश् चेद् अपि नास्ति दोषः। 
एवं "प्राप्यः" इत्यत्रापि।

2023-12-02 14:53 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/03_padArthasamuddeshaH.md
> +३. अजडं तु द्विविधम् – पराक् प्रत्यक् चेति । परागपि द्विधा - नित्यभूतिः धर्मभूतज्ञानं चेति ।
om

2023-12-02 14:53 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/01_mangalAcharaNam.md
om

2023-12-02 15:03 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/02_tattvaikyasya_pratijnA.md
> +१. श्रीमन्नारायण एव चिदचिद्विशिष्टोऽद्वैतं तत्त्वम्, भक्तिप्रपत्तिभ्यां प्रसन्नः स एवोपायः, अप्राकृतदेशविशिष्टः स एव प्राप्यः इति वेदान्तवावाक्यैः प्रतिपादयताम् श्रीव्यासबोधायन-गुहदेवभारुचिब्रह्मनन्द
पूर्वं कः पाठोऽत्रावर्तिष्ट?

2023-12-02 16:25 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sa/aNNangarAchAryaH/01.md
> +> जयति पुमान् पर एकः श्रुतिशतपरिगीतवैभव श्रीमान् ।
ओम् । नेदं स्पृशामि इतः परम् । अधुना किं कर्तव्यम्?

2023-12-02 16:26 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/01_mangalAcharaNam.md
> +यद्योगात् प्रोज्ज्वलः सोऽयगूढार्थान् स प्रदर्शयेत् ॥ ५ ॥
ओम्

2023-12-02 16:26 UTC, Dhunee commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sarva-prastutiH/01_upodghAtaH/02_tattvaikyasya_pratijnA.md
> +१. श्रीमन्नारायण एव चिदचिद्विशिष्टोऽद्वैतं तत्त्वम्, भक्तिप्रपत्तिभ्यां प्रसन्नः स एवोपायः, अप्राकृतदेशविशिष्टः स एव प्राप्यः इति वेदान्तवावाक्यैः प्रतिपादयताम् श्रीव्यासबोधायन-गुहदेवभारुचिब्रह्मनन्द
समीकृतम्

2023-12-02 16:35 UTC, vvasuki commented on shrI-sampradAyaH/tattvam/parichaya-sanxepAH/yatIndra-mata-dIpikA/sa/aNNangarAchAryaH/01.md
> +> जयति पुमान् पर एकः श्रुतिशतपरिगीतवैभव श्रीमान् ।
साधु। यथावस्थितं त्यजतु।

2023-12-02 16:38 UTC, merged