upto 281
vishvAsa/AgamaH_vaiShNavaH pull request #6
Opened 2023-03-07 09:54 UTC by Dhunee

2023-03-07 10:23 UTC, vvasuki requested changes

2023-03-07 10:23 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/04_AdhAra-shakti-tarpaNa-kramaH.md
> +<details open><summary>मूलम्</summary>
एतद् द्वयं यथापूर्वं करोतु।

2023-03-07 10:23 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +इत्यनुगृहीतम् । ब्रह्मयज्ञः नाश्रमानियतः; उदाहृततत्त्वटीकाश्रीसूक्त्यहिर्बुध्न्यसंहितावचनादिभिस्तस्याश्रमनियतत्वावगमात् । श्रीतत्त्वटीकायां 'क्रियावाने ब्रह्मविदा'मिति श्रुत्यतर्थ[[श्रुत्यर्थ??]]विचा
aan

2023-03-07 10:23 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +'नाध्येतव्य'मित्यादिकर्मकाण्डविषया, 'उपनिषदमावर्तये'दित्यादिश्रुतेरिति कर्मकाण्डाध्ययनत्यागोक्तेश्च । श्रीभाष्ये ऊर्ध्वरेतसो यज्ञाद्यभावात् तदङ्गिका विद्या न सम्भवतीत्याशङ्क्याह अत एवाचाग्नीन्धनाद्यन
`> ऊर्ध्वरेतसो यज्ञाद्यभावात्तदङ्गिका विद्या न सम्भवतीत्याशङ्क्याह- अत एव चाग्नीन्धनाद्यनपेक्षा । `

इत्य् एतावद् उद्धरणम्।

2023-03-08 01:02 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +इत्यनुगृहीतम् । ब्रह्मयज्ञः नाश्रमानियतः; उदाहृततत्त्वटीकाश्रीसूक्त्यहिर्बुध्न्यसंहितावचनादिभिस्तस्याश्रमनियतत्वावगमात् । श्रीतत्त्वटीकायां 'क्रियावाने ब्रह्मविदा'मिति श्रुत्यतर्थ[[श्रुत्यर्थ??]]विचा
ओम्

2023-03-08 01:04 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +'नाध्येतव्य'मित्यादिकर्मकाण्डविषया, 'उपनिषदमावर्तये'दित्यादिश्रुतेरिति कर्मकाण्डाध्ययनत्यागोक्तेश्च । श्रीभाष्ये ऊर्ध्वरेतसो यज्ञाद्यभावात् तदङ्गिका विद्या न सम्भवतीत्याशङ्क्याह अत एवाचाग्नीन्धनाद्यन
ओम्

2023-03-08 01:06 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/04_AdhAra-shakti-tarpaNa-kramaH.md
> +<details open><summary>मूलम्</summary>
आम्, तावद् एव - तथा हि पृष्ठसङ्ख्याम् प्रत्यानयतु।

2023-03-08 01:10 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/04_AdhAra-shakti-tarpaNa-kramaH.md
> +<details open><summary>मूलम्</summary>
ओम् । अग्रे पृष्ठसङ्ख्याया आवृत्तिर्दृश्यते ।

2023-03-08 01:12 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/04_AdhAra-shakti-tarpaNa-kramaH.md
> +<details open><summary>मूलम्</summary>
133, 134, 135 इत्येताः सङ्ख्याः द्वयोः स्थानयोः दृश्यन्ते.. यथापूर्वं रक्षामि उत?

2023-03-08 01:28 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/04_AdhAra-shakti-tarpaNa-kramaH.md
> +<details open><summary>मूलम्</summary>
(विश्वास-प्रस्तुतिः, मूलम् इति भागयोर् द्विर् वर्तन्त इति भाति) - तथैव वर्तन्ताम् ।

2023-03-10 07:14 UTC, merged