upto 75
vishvAsa/AgamaH_vaiShNavaH pull request #7
Opened 2023-03-10 08:29 UTC by Dhunee

2023-03-14 05:59 UTC, vvasuki requested changes

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +प्राणायामेन चाद्येन मन्त्रं नाभ्यान्तु विन्यसेत् । तदुद्भूतेन नादेन सुषुम्नामध्यवर्तिना ॥
पङ्क्तिभेद इष्यते।

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +प्राणायामद्वितीयेन हृदये विन्यसेन्मनुम् । मन्त्रोत्थेनाग्निना देहं दहेन्मण्डलवर्तिना ॥
पङ्क्तिभेद इष्यते।

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +स्वं तदङ्गुष्ठनिष्ठ्यूतपीयूषाप्लावितं स्मरेत् । पञ्चोपनिषदैर्मन्त्रैः ततस्सञ्जातविग्रहम् ॥
पङ्क्तिभेद इष्यते।

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +प्रभूतानि विशुद्धानि शुद्धदेशवोद्भवानि[[??]] च ।
देशोद्भव

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> श्री सात्वते
इतः, १०५-तमाम् पङ्क्तिं यावत् प्रारम्भे >-स्याद् एव - रिक्तपङ्क्तिष्व् अपि, पृष्ठसङ्ख्यासूचके ऽपि। तदैव "एकम् उद्धरणम् इदम्" इति दर्श्यते। एवम् अन्यत्रापि विधेयम्।

2023-03-14 05:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> तुलसीप्रस्ताव इत्युपक्रम्य
पूर्णम् इदं कथम् उद्धरणम्?

"तुलसीप्रस्ताव" इत्युपक्रम्य +इति दर्शनीयम्। अधश् च >>-स्थाने >-चिह्नम् एव युज्यते।

2023-03-14 06:30 UTC, vvasuki requested changes

2023-03-14 06:30 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
> +ज्ञानं पुष्पं तपः पुष्पं ध्यानं पुष्पं तथैव च । सत्यमष्टविधं पुष्पं विष्णोः प्रीतिकरं भवेत् ॥
पङ्क्तिभेद इष्यते।

2023-03-14 06:30 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +तृतीयकालकर्तव्येज्या*निरूपणं प्रतिजानीते **अथे**ति ।
*-चिह्नं कुतः?

2023-03-14 06:30 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
अत्राप्य् उद्धरणैक्यदर्शनम् इष्यते पूर्वोक्तरीत्या

2023-03-14 06:30 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
>  ## इज्या
`## प्रयोगः` इति भवतु

2023-03-14 06:38 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +प्राणायामद्वितीयेन हृदये विन्यसेन्मनुम् । मन्त्रोत्थेनाग्निना देहं दहेन्मण्डलवर्तिना ॥
समीकृतम्

2023-03-14 06:38 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +स्वं तदङ्गुष्ठनिष्ठ्यूतपीयूषाप्लावितं स्मरेत् । पञ्चोपनिषदैर्मन्त्रैः ततस्सञ्जातविग्रहम् ॥
ओम्

2023-03-14 06:40 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +प्रभूतानि विशुद्धानि शुद्धदेशवोद्भवानि[[??]] च ।
ओम्

2023-03-14 06:42 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> श्री सात्वते
ओम्

2023-03-14 06:48 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> तुलसीप्रस्ताव इत्युपक्रम्य
"तुलसीप्रस्ताव" इत्युपक्रम्य +

> शुष्कं पर्युषितं चार्द्रं काष्ठं वा तुलसीदलम् ।  
अर्चने वासुदेवस्य लक्षकोटिगुणं भवेत् ॥

एवं वा?

2023-03-14 06:49 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
> +ज्ञानं पुष्पं तपः पुष्पं ध्यानं पुष्पं तथैव च । सत्यमष्टविधं पुष्पं विष्णोः प्रीतिकरं भवेत् ॥
ओम्

2023-03-14 06:50 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +तृतीयकालकर्तव्येज्या*निरूपणं प्रतिजानीते **अथे**ति ।
अनवधानवशात् निविष्टमभूत् । अपवारितम् ।

2023-03-14 06:53 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
नावागमम्

2023-03-14 06:54 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
>  ## इज्या
ओम्

2023-03-14 06:55 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/09_ijyA.md
> +प्राणायामेन चाद्येन मन्त्रं नाभ्यान्तु विन्यसेत् । तदुद्भूतेन नादेन सुषुम्नामध्यवर्तिना ॥
समीकृतम्

2023-03-14 08:11 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> तुलसीप्रस्ताव इत्युपक्रम्य
आम्, किन्तु +-चिह्नं नापेक्षितम्। (स्ववाक्ये सन्ध्यपेक्षां दर्शयितुम् प्रयुक्तं तत्। )

2023-03-14 08:13 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
"इतः, १०५-तमाम् पङ्क्तिं यावत् प्रारम्भे >-स्याद् एव - रिक्तपङ्क्तिष्व् अपि, पृष्ठसङ्ख्यासूचके ऽपि। तदैव "एकम् उद्धरणम् इदम्" इति दर्श्यते। एवम् अन्यत्रापि विधेयम्।" इति यन्मया पूर्वम् उक्तं, तद् अत्रापि प्रसज्यते। अन्यास्व् अपि सञ्चिकासु स्थानेषु च परीक्ष्य समीकरोतु।

2023-03-15 03:12 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
ओम्

2023-03-15 11:47 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
om

2023-03-17 10:59 UTC, vvasuki requested changes

2023-03-17 10:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
अत्रापि प्रागुक्तैव समस्या।

2023-03-17 10:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
अत्रापि प्रागुक्तैव समस्या।

2023-03-17 10:59 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> श्री सात्वते
परिहृतं न दृश्यते । परिहृत्य प्रकाश्यैव प्रत्युत्तरं दोषसूचनासूत्रे लेख्यम्।

2023-03-20 14:04 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> श्री सात्वते
परिहृतमस्ति । तस्मिन्नेव दिने.. अहं तु चिह्नं न पश्यामि ।

2023-03-20 14:15 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
परिहृता

2023-03-20 14:15 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
परिहृता

2023-03-20 14:15 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
परिहृता

2023-03-20 14:16 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
> +>
परिहृता

2023-03-20 14:16 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/05_devaRShi-pitR-tarpaNam.md
> +>
परिहृता

2023-03-20 14:16 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/08_kushAharaNavidhiH.md
> +>
परिहृता

2023-03-21 06:19 UTC, vvasuki requested changes

2023-03-21 06:19 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  बहु स्यां प्रजायेयेति च पृथगभिमानित्वे हि न बहुस्यामिति स्यात् । अत एव तत्फलभोगेन हर्षशोकादिभिर्विकुर्वाणः विकर्ता स्वार्थशोकहर्षाद्यभावेऽपि परार्थतत्प्रसक्तिरदोषः । अन्यथा परदुःखदुःखित्वदयादिगुणाः क
`> "बहु स्यां प्रजायेय" इति च । पृथगबिमानित्वे हि न "बहु स्याम्" इति स्यात् ।। अत एव तत्फलभोगेन हर्षशोकादिभिर्विकुर्वाणः विकर्ता स्वार्थशोकहर्षाद्यभावेऽपि परार्थतत्प्रसक्तिरदोषः । अन्यथा परदुःखदुःखित्वदयादिगुणाः कथमस्य स्युरित्युक्तेः ।`


इति उद्धरणाङ्गं कुर्यात्। कारणं नावगतं चेत् प्रष्टव्यम्।

एवम् अग्रिमवाक्ये चिह्नयोजनम् इत्थम् -`""परदुःखदुःखित्वात्मकदयादयो गुणा" इति तदर्थ" इति ।`
https://archive.org/details/vishnusahasranamawithbhashyaofparasarabhattarsanskritengprofasrinivasaraghavan1983/page/n481/mode/2up

2023-03-21 06:19 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > व्यसनेषु मनुष्याणां ‘बहुस्या’मिति प्रमाणोदाहरणात् । व्यसनेष्विति श्लोकः गोविन्दराजीये एवं व्याख्यातः ।
"व्यसनेषु मनुष्याणां", ‘बहुस्या’मिति प्रमाणोदाहरणात् ।

इति कुर्यात्। कारणं नावगतं चेत् प्रष्टव्यम्। न चैतद् उद्धरणम्

2023-03-21 08:02 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  >> ततो वेद एव ब्रह्मयज्ञेऽध्येतव्यः,
समीक्रियते

2023-03-21 08:02 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > पैठीनसिः -
समीक्रियते

2023-03-21 08:05 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > पञ्चमहायज्ञाद्यनुष्ठानं शक्तितः क्रियेति निर्वचनं,
> चिह्नमिदमपाकर्तव्यं वा? अपि च पूर्वस्मिन् वाक्यखण्ड एवास्य निवेशः कार्यो वा?

2023-03-21 08:06 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > इति पञ्चमहायज्ञादिपरत्वस्यानुगृहीतत्वात् ।
ओम् समीक्रियते ।

2023-03-21 08:06 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > इति श्रीसारावलीश्रीसूक्त्या
समीक्रियते

2023-03-21 08:38 UTC, vvasuki commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > पञ्चमहायज्ञाद्यनुष्ठानं शक्तितः क्रियेति निर्वचनं,
(दूरवाण्या स्पष्टितम्)

2023-03-21 08:41 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > व्यसनेषु मनुष्याणां ‘बहुस्या’मिति प्रमाणोदाहरणात् । व्यसनेष्विति श्लोकः गोविन्दराजीये एवं व्याख्यातः ।
परिष्क्रियते

2023-03-21 08:44 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  इत्यादि ।
तदित्थं सङ्गृहीतं नारायणमुनिभिरिति उद्धरणाङ्गं वा? यदि न तर्हि उद्धरणस्यान्तः उद्धरणान्तरस्याभावात् चिह्नद्वयनिवेशः कुतः?

2023-03-21 08:45 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  >> परीक्ष्य लोकान् कर्मचितान् ब्राह्मणो निर्वेदमायान्नास्त्यकृतः कृतेन, तद्विज्ञानार्थं स गुरुमेवाभिगच्छेत्
ओम्

2023-03-21 08:47 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  >> ब्रह्मरुद्रोपलक्षितविश्वसृष्टिरक्षाहेतुत्वात् केशिवधोपलक्षितसर्वदुष्टदमनस्वभावत्वाच्च असहायदशासाहाय्यार्थं तदा तच्चिन्तनं
एकोद्धरणाणाङ्गमिति विचिन्त्य तथा कृतमासीत् । समीक्रियते

2023-03-21 08:49 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  इति भवेयुरिति शेषः इति ब्रह्मचार्यादिधार्यं समयव्रतचक्रादिचिह्नादिकमित्यनुगृहीतम् । व्यापकयोजनप्रमाणादिकं क्वाप्याचार्यपादश्रीसूक्तौ न दृश्यते । अतः स्वसूत्रविहितमेवेत्यनुगृहीतमेवाचार्यैरनुसृतमिति बो
ओम्

2023-03-21 08:52 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/05_devaRShi-pitR-tarpaNam.md
>  > अत्र कपर्दिस्वामी -
ओम् । परिष्क्रियते

2023-03-21 10:54 UTC, vvasuki requested changes

2023-03-29 04:37 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> श्री सात्वते
सर्वाणि सूचितानि स्थलानि परिष्कृतानि

2023-03-29 04:37 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/07_upAdAnam.md
> +> तुलसीप्रस्ताव इत्युपक्रम्य
चिह्नं परिहृतमस्ति

2023-03-29 04:40 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  >> ब्रह्मरुद्रोपलक्षितविश्वसृष्टिरक्षाहेतुत्वात् केशिवधोपलक्षितसर्वदुष्टदमनस्वभावत्वाच्च असहायदशासाहाय्यार्थं तदा तच्चिन्तनं
समीकृतमस्ति

2023-03-29 04:40 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/02_abhigamanam.md
>  इति भवेयुरिति शेषः इति ब्रह्मचार्यादिधार्यं समयव्रतचक्रादिचिह्नादिकमित्यनुगृहीतम् । व्यापकयोजनप्रमाणादिकं क्वाप्याचार्यपादश्रीसूक्तौ न दृश्यते । अतः स्वसूत्रविहितमेवेत्यनुगृहीतमेवाचार्यैरनुसृतमिति बो
समीकृतमस्ति

2023-03-29 04:40 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/05_devaRShi-pitR-tarpaNam.md
>  > यजुश्शाखिनान्तु काण्डानुक्रमण्यां काण्डर्षितर्पणमुक्तं -
समीकृतमस्ति

2023-03-29 04:40 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/05_devaRShi-pitR-tarpaNam.md
>  > अत्र कपर्दिस्वामी -
परिष्कृतमस्ति

2023-03-29 04:41 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > अत्र कात्यायनः -
पर्यकार्षम्

2023-03-29 04:41 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > पैठीनसिः -
परिष्कृतम्

2023-03-29 04:43 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  इत्यादिश्रुतिः । अछदिर्दर्शेछदिर्दर्शनरहिते देशे । छदिश्शब्दः गृहाच्छादकतृणादिपरः । ‘अथ पटलं छदि'रिति निखण्डुः ।
समीकृतमस्ति

2023-03-29 04:45 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > सन्ध्योपासनानन्तरकृत्यञ्चैवं विवृतं —
समीकृतमस्ति

2023-03-29 04:45 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > प्रवेशे निर्गमे चैव विष्वक्सेननतिं चरेत्
समीकृतम्

2023-03-29 04:45 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > आचार्यदर्शने भगवन्नामग्रहणे चाञ्जलिबन्धादिकं तत्र तत्रोक्तं ग्राह्यम् । दर्शितश्चायमाचारः सम्भवपर्वणि व्यासप्रस्तावे –
समीकृतम्

2023-03-29 04:46 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > श्रीशाण्डिल्यस्मृतौ –
समीकृतम्

2023-03-29 04:46 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > श्रीसात्वते -
समीकृतम्

2023-03-29 04:46 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > करणं कारणं कर्ता विकर्तेत्येतद्व्याख्याने तथा स्वतन्त्रः कर्ता अधिकारी फली जीवोऽपि हि स्वयं स्वस्य यथा सुखदुःखाभिमानी तथा तदतिशयेन वा तदवस्थाभिमानी हि भगवान् । यथा
स्पष्टम् । विहितः परिष्कारः

2023-03-29 04:46 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  बहु स्यां प्रजायेयेति च पृथगभिमानित्वे हि न बहुस्यामिति स्यात् । अत एव तत्फलभोगेन हर्षशोकादिभिर्विकुर्वाणः विकर्ता स्वार्थशोकहर्षाद्यभावेऽपि परार्थतत्प्रसक्तिरदोषः । अन्यथा परदुःखदुःखित्वदयादिगुणाः क
समीकृतमस्ति

2023-03-29 04:48 UTC, Dhunee commented on shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/06_brahmayajnakramaH.md
>  > व्यसनेषु मनुष्याणां ‘बहुस्या’मिति प्रमाणोदाहरणात् । व्यसनेष्विति श्लोकः गोविन्दराजीये एवं व्याख्यातः ।
परिष्कृतमस्ति

2023-03-29 05:08 UTC, merged